FROM ros:noetic-ros-base
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends apt-utils
RUN apt-get install -y ros-noetic-image-geometry ros-noetic-pcl-ros \
    ros-noetic-cv-bridge git cmake build-essential unzip pkg-config autoconf \
    libboost-all-dev \
    libjpeg-dev libpng-dev libtiff-dev \
    libvtk7-dev libgtk-3-dev \
    libatlas-base-dev gfortran \
    libparmetis-dev \
    python3-wstool python3-catkin-tools \
    libtbb-dev \
    ros-noetic-rosbridge-library \
    mosquitto \
    mosquitto-clients \
    ros-noetic-mqtt-bridge

RUN mkdir -p /root/catkin_ws/src/

RUN . /opt/ros/noetic/setup.sh && cd /root/catkin_ws && \
    catkin init && catkin config --cmake-args -DCMAKE_BUILD_TYPE=RelWithDebInfo && \
    catkin build

# Add source commands to .bashrc
RUN echo "source /opt/ros/noetic/setup.bash" >> /root/.bashrc
RUN echo "source /root/catkin_ws/devel/setup.bash" >> /root/.bashrc

RUN echo "export ROS_MASTER_URI=http://172.17.0.2:11311" >> /root/.bashrc
RUN echo "export ROS_IP=172.17.0.2" >> /root/.bashrc
WORKDIR /root/
